// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXtZFjqPR11-mE9fuMBGrOb0iTfCiq5fU',
    appId: '1:667670608661:web:6a8c4325ec1d024240871c',
    messagingSenderId: '667670608661',
    projectId: 'gina-app-5603b',
    authDomain: 'gina-app-5603b.firebaseapp.com',
    storageBucket: 'gina-app-5603b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_aRoPfwgBUeDDZqaAesl7MK9NOySQcMY',
    appId: '1:667670608661:android:5e0c157af960ab2840871c',
    messagingSenderId: '667670608661',
    projectId: 'gina-app-5603b',
    storageBucket: 'gina-app-5603b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu-k5YLMxDjpohWM57TGbzH9QVqo1e220',
    appId: '1:667670608661:ios:3a82945bb29e82f040871c',
    messagingSenderId: '667670608661',
    projectId: 'gina-app-5603b',
    storageBucket: 'gina-app-5603b.appspot.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu-k5YLMxDjpohWM57TGbzH9QVqo1e220',
    appId: '1:667670608661:ios:1f5ec28ceef8597e40871c',
    messagingSenderId: '667670608661',
    projectId: 'gina-app-5603b',
    storageBucket: 'gina-app-5603b.appspot.com',
    iosBundleId: 'com.example.firstApp.RunnerTests',
  );
}
